### ISSUE TITLE
About dynamic runtime exports in CommonJS

### ISSUE THREAD

**Issue by fritx** [typicode/xv#11]
```js
let testCases = [ /* ... */ ]

/* works */
exports.testAll = async () => {
  await Promise.all(testCases).map(async item => { /**/  })
}

/* runtime exports can't be recognized */
testCases.forEach(item => {
  exports[item.xxx] = async () => { /* ... */ }
})
```

I'm consider a PR but not sure which would be the best approach:

1. ignore this
2. add a nextTick and display an explicit warning
3. add a nextTick and recognize that for the user

**Comment by typicode** [comment]
I would ignore it. I'd prefer to have xv driven by ESM capabilities and keep similarities between both approach. It may be a bit complex to implement. AFAIK while you can have runtime exports in CJS, it's not possible with ESM.

The first example works and it's simple to add some info regarding the failing test case if needed/wanted. Something like that:

```js
exports.testAdd = function() {
  const testCases = [[1, 2, 3], [1, 1, 2], ...]
  for (const testCase of testCases) {
    try {
      // ... do testing
      assert.equal(actual, expected, someMessage) // Optionally: add message
    } catch(e) {
      console.log(testCase[0], testCase[1], 'failed') // Optionally: log info regarding failing test case
      throw e
    }
}
```

How would the nextTick work?
