### ISSUE TITLE
ts-node `runTestFile` problem

### ISSUE THREAD

**Issue by xseman** [typicode/xv#13]
Thanks for amazing library. 

I'm testing `v2`, the `runTestFile()` uses `pathToFileURL(file).toString()`
which behave differently when running with`ts-node` loader.

```json
{
	"scripts": {
		"test": "xv --loader=ts-node/esm ./src"
	},
	"devDependencies": {
		"ts-node": "~10.9.0",
		"typescript": "~4.9.0",
		"xv": "~2.0.0"
	}
}
```
```ts
// ./src/test.ts
import assert from 'node:assert/strict';

export function foo(): void {
	assert.strictEqual(true, false)
}
```

I'm logging output of `pathToFileURL(file).toString()`.

```sh
xv --loader=ts-node/esm ./src
```

Test wont run, `if (typeof value === 'function')` is skipped, there is only default export from `pathToFileURL(file).toString()`.

```diff
src/test.ts
+ [Module: null prototype] { default: { foo: [Function: foo] } }
```

Compiled ts works.

```sh
tsc && xv ./lib
```

```diff
lib/test.js
+ [Module: null prototype] {
+  __esModule: true,
+  default: { foo: [Function: foo] },
+  foo: [Function: foo]
+ }
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

true !== false
```

**Comment by typicode** [comment]
Thanks :)

So I tried your code and I was able to have `test.ts` fail (as expected) by changing `tsconfig.json`. I used https://github.com/tsconfig/bases/#node-16--esm--strictest-tsconfigjson and it worked.

**Comment by xseman** [comment]
My bad, I should have included `package.json` and `tsconfig`.
So after experimenting `package.json` must contain `"type": "module"` then `pathToFileURL()` works as expected with loader.

```diff
$ xv --loader=ts-node/esm ./src

(node:32527) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
src/test.ts
+ [Module: null prototype] { foo: [Function: foo] }
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

true !== false
```

**Comment by typicode** [comment]
No worries :+1: thanks for the update. Can this issue be closed?

**Comment by xseman** [comment]
Yes, would you like PR to update the README that `"type": "module"` is needed for `ts-node`? Thanks!

**Comment by typicode** [comment]
Not sure that it's needed. If similar issues come often, yes.
I've updated xv to show a message if no tests are found by the way :+1:
