### ISSUE TITLE
Error handling in the pre-commit hook

### ISSUE THREAD

**Issue by hikiroom** [typicode/xv#3]
Hello @typicode👋

First of all, I appreciate your awesome work.

Let me get to the point, I have one problem that related to pre-commit hook.
That cannot stop commit when failed test at pre-commit.
This reason is because xv uses `console.error` for error output, I am assuming.

I would like to know a good solution to this problem, if any.

thank you.

**Comment by typicode** [comment]
Hi @hikiroom,

Thank you!

Could you give it another try with `v1.0.2`?

**Comment by hikiroom** [comment]
Hi @typicode,

Thanks to you, my problem has been resolved! :D

**Comment by typicode** [comment]
:+1:  thanks for pointing out this bug :)
