### ISSUE TITLE
Is it possible to export run?

### ISSUE THREAD

**Issue by linbuxiao** [typicode/xv#6]
My scenario is like this: I need to run a mock server before the test starts. The port of this server will be returned randomly via a function, so I need to pass the port in as an environment variable when xv is run. This means I need to execute xv inside a file instead of the command line. So is it possible to export the run method to make this happen?

**Comment by linbuxiao** [comment]
> Hi @linbuxiao,
> 
> Not sure to get the environment variable part. Could you detail the use case a bit?
> 
> Why not for example
> 
> ```
> $ PORT=3000 xv src/
> ```
> 
> ```js
> // src/test.js
> console.log(process.env.PORT)
> ```
> 
> Or
> 
> ```js
> // src/test.js
> import { startServer } from './mockserver'
> 
> await startServer()
> 
> export function testServer() {
>   // requests to mock server
> }
> ```

Thank you very much for your reply! The problem is that the port is random, so I can't explicitly specify it on the command line. I need to first return a random port from a library like `get-port` and put the address into the test.

**Comment by typicode** [comment]
I see for the env variable. Thank you :)

What about then:

```js
import { startServer } from './mockserver'
import getPort from 'get-port'

const port = await getPort()
await startServer(port)

export function testServer() {
  // requests to mock server
}
```

Just trying to understand.

Also with `xv(path)` how would it look like?

**Comment by linbuxiao** [comment]
> I see for the env variable. Thank you :)
> 
> What about then:
> 
> ```js
> import { startServer } from './mockserver'
> import getPort from 'get-port'
> 
> const port = await getPort()
> await startServer(port)
> 
> export function testServer() {
>   // requests to mock server
> }
> ```
> 
> Just trying to understand.
> 
> Also with `xv(path)` how would it look like?

https://github.com/linbuxiao/leeter/blob/perf/test/test/mock/xv.ts
https://github.com/linbuxiao/leeter/blob/perf/test/test/mock/server.ts

Here is an example of how I use `xv` haha, maybe I got into a misunderstanding?

**Comment by typicode** [comment]
Thanks for updating the issue :)
